#!/system/bin/sh

#Must be a multiple of 25 mv
gpu_voltage_table="100mhz: 875 mV 160mhz: 900 mV 266mhz: 900 mV 350mhz: 950 mV 400mhz: 1000 mV 450mhz: 1050 mV 533mhz: 1100 mV 612mhz: 1150 mV 667mhz: 1200 mV 720mhz: 1250 mV";
#min and max threshold in percent before ramping up or down
gpu_dvfs_table="100mhz:0,55 160mhz:50,70 266mhz:60,79 350mhz:70,86 400mhz:80,95 450mhz:94,99 533mhz:98,99 612mhz:99,100 667mhz:99,100 720mhz:99,100";

echo 533 > /sys/devices/platform/mali.0/dvfs_upper_lock;
echo 0 > /sys/devices/platform/mali.0/dvfs_under_lock;
echo 400 > /sys/devices/platform/mali.0/dvfs_gpu_boost_freq;
echo 300 > /sys/devices/platform/mali.0/dvfs_boost_time_duration;
echo $gpu_voltage_table > /sys/devices/platform/mali.0/asv;
echo $gpu_dvfs_table > /sys/devices/platform/mali.0/dvfs_gpu_table;
