#!/sbin/bb/busybox ash
# osm0sis @ xda-developers

bb=/sbin/bb/busybox;
cache=/dev/block/platform/msm_sdcc.1/by-name/cache;
data=/dev/block/platform/msm_sdcc.1/by-name/userdata;
system=/dev/block/platform/msm_sdcc.1/by-name/system;
system1=/dev/block/platform/msm_sdcc.1/by-name/system1;
device=aries;

# check partition filesystem
getfs() { $bb blkid $1 | $bb cut -d\" -f4; }

case $1 in
  mkfstab)
    # swap out entries for filesystems as detected
    for i in $system $system1 $cache $data; do
      fstype=`getfs $i`;
      fsentry=`$bb grep $i /fstab-$fstype.$device`;
      if [ "$fsentry" ]; then
        $bb sed -i "s|^$i.*|$fsentry|" /fstab.$device;
      fi;
    done;
    $bb rm -f /fstab-*;
  ;;
  setprops)
    # set filesystem type properties for external use - system mount (toolbox) required
    setprop ro.fs.cache `getfs $cache`;
    setprop ro.fs.data `getfs $data`;
    setprop ro.fs.system `getfs $system`;
  ;;
esac;
